; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Kasiu Yas Title:

.export _music_data_kasiu_yas_title:=music_data_kasiu_yas_title

music_data_kasiu_yas_title:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Title
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 229,191

.export music_data_kasiu_yas_title
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Bass
	.word @env2, @env3, @env3
	.byte $00
	.byte $70 ; 01 : Harmony
	.word @env1, @env3, @env3
	.byte $00
	.byte $b0 ; 02 : Lead
	.word @env0, @env3, @env3
	.byte $00

@env0:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$07
@env1:
	.byte $ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$07
@env2:
	.byte $cf,$7f,$00,$00
@env3:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $06
@song0ch0loop:
	.byte $84, $53, $59
@song0ref7:
	.byte $57, $53, $61, $61, $61, $61, $53, $59, $57, $53, $61, $61, $61, $60, $81, $52, $85, $58, $85
	.byte $ff, $0b
	.word @song0ref7
	.byte $60, $81, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $82, $3b, $41, $3f, $3b, $41, $41, $41, $41, $3b, $41, $3f, $3b, $41, $41, $41, $40, $81, $58, $85, $60, $85, $5d, $59
	.byte $67, $67, $67, $67, $59, $61, $5d, $59, $67, $66, $81, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref75:
	.byte $23, $01, $31, $01, $23, $01, $31, $01, $23, $01, $31, $01, $23, $01, $31, $00, $81
	.byte $ff, $11
	.word @song0ref75
	.byte $fd
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $bf, $bf, $fd
	.word @song0ch3loop
